variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - docker

docker-frontend:
  stage: docker
  image: docker:18.09.8
  services:
    - docker:18.09.8-dind
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - cd web/
    - docker build -f frontend.Dockerfile -t sharkie01/frontend:latest .
    - docker push sharkie01/frontend

docker-backend:
  stage: docker
  image: docker:18.09.8
  services:
    - docker:18.09.8-dind
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - cd api/
    - docker build -f backend.Dockerfile -t sharkie01/backend:latest .
    - docker push sharkie01/backend
